help: False
show_model: False
base_path: /HOME/scz0831/run/3d/TLEE/ckpt
train_mode: 1.1 # choice = [1, 1.1, 2, test]
test_path: 1.2_2022_03_28 11_00_16_none_gm_branch.resnet50.3/2_2022_03_28 15_45_31_mp_1e-6_gm_branch.resnet50.3 # 文件夹名即可 训练模式2, test都需要
b: '1e-6'

# checkpoint
resume: False
resume_path: 
##################
data:
  name: ssv2

  path_frame: /HOME/scz0831/run/3d/ssv2/ssv2-frames/  # set the dataset dir
  path_split: /HOME/scz0831/run/3d/ssv2/annotations/train_videofolder.txt
  path_label: /HOME/scz0831/run/3d/ssv2/annotations/train_videofolder.txt
  path_classid: /HOME/scz0831/run/3d/ssv2/category.txt

  preprocessing:
    to_tensor: True
    resize: 224
    crop_center: 224
    normalize:
      mean: [0.43216, 0.394666, 0.37645]
      std: [0.22803, 0.22145, 0.216989]

  preprocessing_label:
    video_multihot_labels: ""
    one_hot_encoding: 174

  num_frames: 10
  num_workers: 6
  shuffle: False
data_val:
  name: ssv2

  path_frame: /HOME/scz0831/run/3d/ssv2/ssv2-frames/  # set the dataset dir
  path_split: /HOME/scz0831/run/3d/ssv2/annotations/val_videofolder.txt
  path_label: /HOME/scz0831/run/3d/ssv2/annotations/val_videofolder.txt
  path_classid: /HOME/scz0831/run/3d/ssv2/category.txt

  preprocessing:
    to_tensor: True
    resize: 224
    crop_center: 224
    normalize:
      mean: [0.43216, 0.394666, 0.37645]
      std: [0.22803, 0.22145, 0.216989]

  preprocessing_label:
    video_multihot_labels: ""
    one_hot_encoding: 174

  num_frames: 10
  num_workers: 6
  shuffle: False
###################
model:
  useLRSchedule: False
  schedule: [6, 10, 15]  # not enable if useLRSchedule is False

  branch_scale: 2 # the channel reduction ratio
  crm_num: 3      # #crm

  useFeatureFunc: mp # [frm, afrm, ema, mp, ap, na, none]
  useGateFunc: gm # [eg, gm] 
  first_threshold: 0.99
  single_frame_mac: [0.79, 1.83, 3.29, 4.1]
  epochs: 5
  backbone:
    type: 2d
    name: branch.resnet50.2
    pretrained: True
    requires_grad: True
    truncate_modules: -1  # index indicates up until which layer to keep modules, i.e. -1 removes the classifier.
    output_dim: [2048]     # branches [3,] # 2048: ResNet50 512: ResNet18, ResNet34

  pooling:
    name: max
  input_order8: [3, 6, 7, 0, 4, 5, 2, 1] #n8
  input_order10: [5, 0, 9, 2, 7, 4, 6, 3, 8, 1] #n10
  input_order16: [9, 8, 6, 3, 15, 1, 0, 12, 14, 2, 10, 7, 13, 11, 4, 5] # n16
  num_classes: 174
